export let batch_1 = [
    "Sobha Varma first batch, 1977-79 MSc (CUSAT ) MPhil (Kerala University ) Ph D (MG University ) Retired, D B College, Thalayolaparambu.",
    "Dr Rani M J 1978- 80 batch. Currently Vice Principal, Sahrdaya College of Advanced Studies Kodakara", 
    "Jayanthan, A. J. M.Sc. Mathematics, 1979-'81. Retired from Goa University.", 
    "Dr. S. Babusundar M.Sc., 1977 - 79 first batch Ph.D., 1989 Retired Professor, CUSAT.", 
    "Jayanthan, A J., M. Sc. Mathematics, 1979-81. Currently teaching at Kerala School of Mathematics.", 
    "John Christopher F Rtd headmaster MSC 1978_80 batch Joy Joseph MSc Mathematics 1982-84", 
    "Dr Rani M J 1978- 80 batch. Currently Vice Principal, Sahrdaya College of Advanced Studies Kodakara", 
    "Dr. Jessy John, 1977-79 first batch, mob: 9446164249",
    "Jacob K DanielM. Sc 1978-80 , Ph. D 1980-85 Now enjoying retired life. Staying at Edappally",
];

export let batch_2 = [
    "Suresh, 1980-82 Statistics At Bangalore, Have a small Company.",
    "Asa Anila Msc Maths 1980-82 batch M. Phil 1993 batch +91 92497 27755: Retd from S. N college Nattika",
    "Rajagopalan A, PG Diploma OR&CA 1983-84, M.Sc.Maths 1984-86. Presently working in NIT Calicut(erstwhile REC Calicut) in Computer Science Department.",
    "Manoj Changat MSc. Maths 1984-86, Ph.D. 1987-90. Presently working at University of Kerala ( Department of Futures Studies as faculty )",
    "Sivadasan P MSc(maths) 1984-86 batch Rtd. HSST Comp.Science DrTPS, Hyderabad. Mathematics MSc 1984-1984 batch https://youtube.com/c/DrTPSASIKUMAR +919447437948",
    "Aloshious George OR&CA 1983-84 1988-89 IT Business, in Kochi",
    "V M Sunandakumari PhD 1983-1988 Rtd, Director of Higher Secondary Education Member, JJB, 2019- to date", 
    "PV Radhadevi MSc 1984-86 at CUSAT, PhD in Applied Mathematics from Bangalore Uni. Joined in ISRO during 1989 and working as a Scientist for the last 32 years Currently Director, Advanced Data processing Research institute (ADRIN),Hyderad, which is the same ISRO centre where I joined.",
    "Johnson T.P PhD 1987.1992 Presently Professor,SOE, CUSAT",
];

export let batch_3 = [
    "Askar Ali M 2015- 2017 MSc Batch Currently, Research scholar at BITS PILANI, Goa Campus Indulal G M. Phil: 1994-1996 PhD : 2005-2007 Now Associate Professor St. Aloysius College, Edathua 9744448250", 
    "Dr. M S Sunitha, 1991-93 MSc 1994-95 MPhil 1996-2001 Ph. D. Prof. & Head, Dept. of Mathematics, NIT CALICUT 9349139316", 
    "Jeepamol J Palathingal M. SC batch 1997-99. Assistant Professor P. M. Govt. College, Chalakudy.",
    "Mangalambal N.R PhD:1992- 1998 Associate Professor (Retired) St. Joseph's College (Autonomous), Irinjalakuda.",
    "Seema Varghese Associate Professor , Govt Engineering College Thrissur MSc: 1998-2000, PhD: 2011", 
    "Manjunath A S Assistant Professor Govt Victoria College Palakkad MSc 1997-1999 PhD 2017", 
    "Varghese Jacob HoD & Associate Professor Govt. College Kottayam MSc : 1991-1993 MPhil : 1995-1996 PhD : 2008-2012", 
    "Ramachandran M Sc 1997 - 99. Asst Prof Dept of Mathematics,St Paul's College,Kalamassery", 
    "Vinod Kumar P B M. Sc. (1994-96) M. Phil. (1996-1997) Ph. D (1997-2001) Professor in Mathematics Dean (P G Studies) Rajagiri School of Engineering & Technology (Autonomous).", 
    "Jayaprasd P N M Sc. (1994-1996) Ph. D (2010-2013) Associate Professor Dept. of Mathematics Government College Kottayam.", 
    "Teena Liza John 1997-99 batch Associate Professor Dept. Of Mathematics TKM college of engineering, Kollam", 
    "Ramkumar P. B 1997-1999 batch", 
    "Resmi Varghese M Sc 1998-20 Assistant Professor St Xavier's College for Women Aluva", 
    "Sreeja K U MSc Mathematics (1998-2000) Assistant Professor KKTM Government college, Pullut, Thrissur.", 
    "Jayalekshmi K K M.Sc Mathematics 1998-2000 Batch Currently working as Assistant Professor in NSS College, Pandalam", 
    "Manitha Varghese 1995_1997 batch Currently working as lecturer University of Technology and applied sciences Nizwa ,Sultanate of Oman.", 
    "Dr Resmi Varghese M.Sc Mathematics 1998-2000 batch. Ph.D 2014. Currently working as Assistant Professor at St Xavier's College for Women Aluva.",
    "PARVATHY K S PhD 1997, under the Supervision of Prof. Vijayakumar Sir. Presently working at St. Mary' College Thrissur",
    "Sindhu G.Nair 91-93 batch Currently working at NSS College, Ottapalam"
];

export let batch_4 = [
    "Johnson P James 2003-05 batch Working as PGT Maths in Jawahar Navodaya Vidyalaya, Jalna (Dist.), Maharashtra.",
    "Aparna Lakshmanan S 2000-2002 MSc 2004-2009 PhD Now, Assistant Professor, Department of Mathematics, CUSAT",
    "Shajeeb P U 2000 - 2002 MSc Assistant Professor Govt. Victoria College, Palakkad",
    "Viji M M.Sc Mathematics (2004-2006) PhD (2006-2014) Currently Assistant Professor St. Thomas college (autonomous), Thrissur", 
    "Pravas K, M.Sc. Mathematics (2005). Phd 2017 Assitant Processor at Department of Mathematics, K.K.T.M. Govt. College, Pullut", 
    "Murali T.K. M.Sc. 2002-2004 Assistant Professor , Institute of Printing Technology and Govt.Polytechnic College, SHORANUR.",
    "Chithra KS MSc 2004-2006 Asst. Professor St. Joseph's College for Women, Alappuzha", 
    "Binitha Benny M.Phil 2008-2009,Ph.D.-2018 Assistant Professor Dept.of Mathematics St.Joseph's College for Women Alappuzha",
    "Varun Soman, MSc 2008-10 Batch, Assistant Professor, College of Engineering Trivandrum", 
    "Anu V M.Sc. (2001-2003) M.Phi. (2009-2010) Assistant Professor Department of Mathematics St. Peter's College Kolenchery", 
    "Sreenivasan C, Associate Professor, Govt. Victoria College Palakkad PhD ( 2007-2012) degree awarded on 1, March 2013", 
    "Vishnudas V, MSc. Math 2004-2006.", 
    "Vinitha T MSc 2007-09 Assistant Professor Al-Ameen college Edathala.", 
    "Akhila R 2009-2011 Msc. 2011-2012 M Phil 2013- 2018 Phd Assistant Professor S N College, Kollam", 
    "Annie Reeja K.J 2009-2011 Msc batch B.ed", 
    "Jinsmol Janardanan MSc 2006-2008 MPhil 2008-2009 Assistant Professor, Government Engineering College, Thrissur",
    "Seena Varghese M.Sc. (2001-2003) M.Phil. (2009-2010) Assistant Professor FISAT Angamaly", 
    "Saranya G Nair MSc ( 2008-2010) Currently Asst. Prof, BITS Pilani, Goa Pramada",
    "Divya Jayaprakash v k 2001 2003 batch Assistant professor in contract Vimala College Thrissur", 
    "Shafeeque PN 2001-03 Lecturer in Mathematics, Jubail Industrial College, Royal Commission for Jubail KSA", 
    "Dinesh from 2001-2003 batch Zeta 2006-2008 Batch Assistant professor Aquinas College, Edakochi", 
    "Sibi Sam Johns MSc OR&CA 2003-05 Program Manager Marquis / Dept of Corrections, Florida", 
    "Balaji M N , M. Sc (2000-2002), M.phil( 2008-2009), Assistant Professor, Govt Women's Polytechnic College Kalamassery", 
    "Jilu Jose M.Sc (2009-2011) Assistant Professor, St. Mary's college Kottayam", 
    "Nisha Mary Thomas M.Sc 2001 - 2003 batch Teaching at CHRIST University, Bangalore", 
    "Susan Mathew Panakkal Assistant Professor St. Teresa's College Ph.D Research scholar at CUSAT (2009-2019)", 
    "Vijesh p Msc 2000_2002 Higher secondary school teacher", 
    "Raveesh R Varrier MSc Batch 2009-2011 Assistant Professor St.Aloysius College, Elthuruth, Thrissur",
    "Prince Joseph MSc 2001-2003 HSA SKV HSS Neendoor Kottayam", 
    "Najiya V K MSc 2016-2018 Currently Research Scholar NIT, Calicut Durga V K MSc OR & CA, first Semester (2005-2006) Currently, Sr Technical Progam Manager, Amazon, Bangalore", 
    "Praveen I MSc batch 2000-2002 Assistant Professor Amrita Vishwa Vidyapeetham, Coimbatore",
    "Bincy C J M.Sc. batch(2009-11) Research Scholar Bharata Mata College Thrikkakara", 
    "Rajesh V (2005-2007 Batch) Now at Chennai, Directorate of Census Operations", 
    "Tresa Mary Chacko M.Sc 2004-2006 Assistant Professor Department of Mathematics Christian College Chengannur", 
    "Sreekanth raja M. Sc math 2002-04 batch", 
    "Dr Jasmine Mathew MSc Mathematics (2002-2004) Assistant Professor Govt College Balussery,", 
    "Dr Yoonus Ahammed MSc Mathematics (2002-2004) Director, FCC Controls - AME Standard Chartered Bank, Dubai, UAE Dr Pinky Ph.D (2015- 2021)", 
    "Manju S Nair (2002-2004 batch Maths) Currently working as Assistant Professor at Govt. Engineering College, Palakkad", 
    "Pritty Mary George 2005-07 MSc Mathematics Batch Currently working as Assistant Professor at MSM College, Kayamkulam", 
    "Parvathy Msc Maths 2002-04 batch!! Currently working for Accenture, New Jersey as a Senior Manager in the Cyber Security space!", 
    "Nisha Alex 2003-2005 MSc OR&CA Batch Currently working as a Senior Program Manager with DXC Technology, Hyderabad.",
    "Ambily A A MSc Mathematics 2005-2007 Assistant Professor,CUSAT",
];

export let batch_5 = [
    "Rohith Raja M 2015-17 Batch Research Scholar in Graph Theory CHRIST (Deemed to be University), Bangalore.",
    "Aparna Pradeep V K 2014-16 MSc batch Research Scholar in CUSAT",
    "Deepthi Mary Tresa S. (2015-16 M.Phil batch) Research Scholar St. Albert's College, Ernakulam", 
    "Veena V S 2015- 2017 MSc Batch Research scholar at Pondicherry University", 
    "Smruthi S (M. Sc. Mathematics, 2010-12 ) Assistant Professor Dept. of Mathematics Sree Kerala Varma College, Thrissur", 
    "Akhil Damodharan MSc 2010-2012 MPhil 2013 - 2014 Asst Professor Sri Vyasa NSS College Wadakkanchery", 
    "Lakshmi Girish MSc 2014 - 2016 Faculty cum Research Scholar at Amrita School of Arts and Sciences, Kochi.", 
    "Albin Mathew M.Sc. 2016 - 2018 Batch Research Scholar at Central University of Kerala.", 
    "Melbin Antoo Batch -2016-18 Msc B.Ed", 
    "Mahesh T V M. Phil 2014 P. HD Scholar IIST, TRIVANDRUM", 
    "Gayathri Jayaprakash MSc 2017 -2019 Doing B.Ed", 
    "Athira V MSc Mathematics 2014-16", 
    "Jintumol K.U MPhil-2015-2016batch Guest lecturer- B.C.M College Kottayam", 
    "Sajeesh kumar V K MPhil 2012-13 Assistant Professor Government College Mokeri", 
    "Sreelekshmi C Warrier MPhil 2011-2012 Assistant Professor, Sree Ayyappa College, Chegannoor", 
    "Vivek P.V MPhil 2011-2012 Assistant Professor S. N College, Kollam", 
    "Midhun S M.Sc 2014-16 Assistant Professor S.N College, Kollam.", 
    "Reshma M R MSc 2014-2016 Assistant professor Indira Gandhi College Nellikuzhy", 
    "Chitra Venugopal MSc 2016-2018 Mphil 2018-2019 Research student IIT Hyderabad", 
    "Robin P 2013-16 M. Sc. Maths Tution Teacher", 
    "Seethu Varghese Msc 2010,Mphil 2011,PhD 2017 Assistant Professor Bharata Mata College, Thrikkakara", 
    "Arunkumar C S MSc 2013-2015 Mphil 2015-2016 PhD 2018-2019 Currently Research Scholar Kerala School of Mathematics(KSoM)", 
    "Alisha Ann John MSc MPhil 2012 to 2015 School teacher", 
    "Jini Johny C J (2013-15 M.Sc batch) Research Scholar MarThoma College, Thiruvalla", 
    "Siji Michael Research scholar, Dept of Mathematics CUSAT. MSc 2011- 13.", 
    "Smisha M A MSc 2011-13 batch Assistant Professor, St. Michael's College, Cherthala.", 
    "Anjali P S Msc 2011-2013 M.phil 2014-2015 Assistant professor on contract, CAS Calicut (IHRD).", 
    "Dalu Jacob M.Phil 2014-2015 Research Scholar Indian Statistical Institute, Chennai", 
    "Smitha Davis M.Phil 2014-2015 Assistant professor Sacred Heart College, Chalakudy Kerala", 
    "Jolsna P N HS TEACHER AT MALAPURAM (UNAIDED ) MSc 2011- 2013", 
    "Neethu K Msc batch 2011-2013 Assistant professor Christ College of engineering, Irinjalakuda", 
    "Akshara R Msc batch 2011-2013 Assistant professor on contract Christ College, Irinjalakuda", 
    "Arun A MSc ( 2013-15) Currently Research Scholar, University of Kerala", 
    "Didimos K V Completed Ph. D in 2018 Assistant Professor of Mathematics Sacred Heart College Thevara, Kochi", 
    "Akhila Vijayan 2013-15 MSc batch Now HSA at SKMJ HSS Kalpetta, Wayanad", 
    "Nikhil M Msc batch 2011-2013 Assistant professor Sree Narayana College of engineering and Technology Payyannur", 
    "JIYA ROSE JOHNSON MSC 2018-20 Currently doing PhD at IIT Madras", 
    "Ramlath k s 2012-2014 batch", 
    "Krishnadas Ashok 2012-2014 Msc batch( discontinued after first year) Currently Research scholar (Calicut university)", 
    "A. Vijayakumar MSc 1978-80, PhD 80-86. Faculty 88-2018 Emeritus Professor 2018-Currently Vice President of Ramanujan Mathematical Society.",
    "Neethu T S 2010-12 batch Currently : Research Scholar, dept of Mathematics, St. Thomas college, Thrissur",
    "Dr. P. Vinod Bhattathiripad M. Sc. (OR & CA) during 85-87. M. Phil & Ph D (Cyber Forensics) not from CUSAT. Cyber Forensic Consultant in India & abroad. Specialised in cyber evidence of crimes. Authored a book for the American judiciary. Technical expert to the Indian judiciary & various central investigation agencies. Cyber Forensic Advisor to the DGP, Kerala Police during 2017-2021.",

];





