import Table from "../../Reusable/Table/Table";
import Title from "../../Reusable/Title/Title";

const Publications = () => {
    return (
        <>
            <Title head="Publications" />
            <Table heading={["Sl.no", "Title of the paper", "Name of the author/s", "Name of the journal", "year of publication", "ISSN No", "link to recog", "Link to the paper"]}
                rest={publications}/>
        </>
    );
}

export default Publications;



// //Name of the author/s
// "Jeepamol J Palathingal, Aparna Lakshmanan S., Gopalapillai Indulal",
// "Athira Babu, Bin Han, Noufal Asharaf",
// "Wolfram Bauer, V. B. Kiran Kumar, Rahul Rajan.",
// "C.S. Arunkumar, P. Shankar, and A.K. Vijayarajan",
// "Suja C Nair, Sudeep Elayidom M, Dr.Sasi  Gopalan",
// "Dr. Sasi Gopalan, Anju S Mattam",
// "Dr. Sasi Gopalan, Anju S Mattam",
// "A.A. Ambily and Ravi A. Rao"<
// "Seena Varghese, Aparna Lakshmanan S., S. Arumugam",
// "Anu V., Aparna Lakshmanan S.",
// "Jeepamol J Palathingal, Gopalapillai Indulal, Aparna Lakshmanan S.",
// "Stephan Dempe, Nguyen Dinh, Joydeep Dutta and Tanushree Pandit",
// "SHERY FERNANDEZ, DEEPTHI MARY TRESA S DIVYA MARY DAISE S",
// "SHERY FERNANDEZ, DEEPTHI MARY TRESA S DIVYA MARY DAISE S",
// "P. Shankar",
// "P. Shankar and A. K. Vijayarajan",
// "Viji Gopal,M Sudheep Elayidom,Varghese Paul,Sasi Gopalan",
// "Suja C Nair C Nair, Dr. Sudheep Elayidom M Elayidom M and Dr. Sasi Gopalan Gopalan",
// "Linu Pinto; Sasi Gopalan; S. Sundararajan",
// "A.A. Ambily",
// "A.A. Ambily, Roozbeh Hazrat and Huanhuan Li",
// "Tathagata Banerjee, Ralf Meyer",
// "V. B. Kiran Kumar, M. N. N. Namboodiri, Rahul Rajan.", 
// "Deepesh K.P., V. B. Kiran Kumar.",  
// "Dr. P G Romeo and  P.R Sreejamole", 
// "A. Noufal", 
// "Anu V., Aparna Lakshmanan S",
// "SHERY FERNANDEZ, BENNY K J",
// "SHERY FERNANDEZ, DEEPTHI MARY TRESA S, DIVYA MARY DAISE S",
// "V. B. Kiran Kumar, M. N. N. Namboodiri, Rahul Rajan", 
// "M. N. N. Namboodiri, S. Pramod, P. Shankar and A. K. Vijayarajan",
// "P. Shankar and A. K. Vijayarajan",
// "Tijo James, Sandi Klavzar, A Vijayakumar",
// "Wasin So, Anu Varghese, A Vijayakumar",
// "Seethu Varghese, M Hinz, A Vijayakumar",
// "Anju.S.Mattom  and Sasi Gopalan",
// "Suja C Nair , Sudeep Elayidom and Sasi Gopalan",
// "Suja C Nair, Sudeep Elayidom M, Sasi gopalan",
// "Gopalan, S., Pinto, L., Sheela, C., Arun Kumar, M.N.",
// "Nisha A B,Dr.Sasigopalan",
// "Jeepamol J. Palathingal, Aparna Lakshmanan S.",
// "SHERY FERNANDEZ, BENNY K J",
// "V. B. Kiran Kumar and G. Krishna Kumar",

// "Sabu Sebastian and V. B. Kiran Kumar",
// "P. Shankar and A. K. Vijayarajan",
// "S. Pramod, P. Shankar and A. K. Vijayarajan",
// "Chitra M R, A Vijayakumar"
// "Pravas K, A Vijayakumar",
// "Pravas K, A Vijayakumar",
// "Savitha K S, A Vijayakumar",
// "Paul Dorbec, Seethu Varghese, A Vijayakumar",
// "Chitra M R, A Vijayakumar", 
// "Seethu Varghese, A Vijayakumar",
// "Chitra M R, A Vijayakumar",
// "Dr.Sasi Gopalan, Linu Pinto , Sheela.C, Arun Kumar",
// "Aparna Lakshmanan S., Cs. Bujtas, Zs. Tuza",
// "V. B. Kiran Kumar",


// //Title of the paper
// "Spectrum of anti-Gallai Graph of Some Graphs",
// "Numerical solution of the viscous Burgers’ equation using Localized Differential Quadrature method",
// "Korovkin-type theorems on B(H) and their applications to function spaces",
// "Boundary representations and rectangular hyperrigidity",
// "Call detail record-based traffic density analysis using global K-means clustering",
// "Rough Approximate operators based on fuzzy soft relation",
// "Algorithm to compute Transitive closure of fuzzy soft relation",
// "Normality of DSER elementary orthogonal group",
// "Two Classes of Non-Leech Trees",
// "The Double Roman Domination Number of Generalized Sierpinski Graphs",
// "Spectrum of Gallai Graph of Some Graphs",
// "Simple bilevel programming and extensions",
// "The lattice of pre-complements of a classic interval valued fuzzy graph",
// "The Chain structure of intuitionistic level subgroups in cyclic groups of order pq",
// "Hyperrigid generators in C * -algebras",
// "Hilbert modules characterization for weak hyperrigid operator Systems",
// "An Encryption based Security Enhancer Tool for IaaS, Applications in Cloud Computing",
// "KM-MBFO: A Hybrid Hadoop Map Reduce Approach for Clustering Big Data by Adopting Modified Bacterial Foraging Optimization Algorithm",
// "VC Dimension Based Fuzzy Sigmoid Neural Network (VC-FSNN)",
// "Yoga of commutators in DSER elementary orthogonal group",
// "Simple ﬂat Leavitt path algebras are von Neumann regular",
// "Non commutative Coarse Geometry",
// "A short survey on preconditioners and Korovkin- type theorems",
// "Approximation of entropy numbers",
// "On the category of R-modules over non commutative rings",
// "Study of Multiplication operator on H1 2H􀀀12",
// "Double Roman Domination Number",
// "The doze optimization of nano silver on Salmonella Typhmurium  using fuzzy mathematics",
// "Classic and Non-classic Interval Valued Fuzzy Graphs",
// "A Korovkin-type theory for non-self-adjoint Toeplitz operators",
// "Quasi hyperrigidity and weak peak points for non-commutative operator systems",
// "Tensor products of hyperrigid operator systems",
// "The Domination Game on Split Graphs",
// "Distance Energy Change in bipartite graph due to edge deletion",
// "Power domination in Knodel graphs and Hanoi Graphs",
// "Product of Fuzzy Soft Groups",
// "Design and Implementation of  Traffic Analysis and Prediction system using CDR Data",
// "Impact of CDR Data Analysis Using Big Data Technologies for Public :An Analysis",
// "Function approximation with deep neural network for image classification in fuzzy domain",
// "Interpose Detection Using Complete Lattice Approach of Mathematical Morphology",
// "Gallai and anti-Gallai graph operators",
// "The doze optimization through fuzzy mathematics",
// "A note on discrete Borg-type theorems.",
// "Real powers of bounded linear operators",
// "Hyperrigid operator systems and Hilbert modules",
// "Separating and quasi hyperrigid operator systems in C*-algebras",
// "The diameter variability of the product graphs",
// "On an edge partition and root graphs of some classes of line graphs",
// "Convex median and anti-median at prescribed distance",
// "Some network topological notions of the Mycielskian of a graph",
// "Heredity for generalised power domination",
// "The diameter variability of product graphs",
// "The k- power bondage number of a graph",
// "Component factors of the Cartesian product of graphs",
// "A Mathematical Model of Neuro Fuzzy Approximation in image Classification",
// "Induced cycles in triangle graphs",
// "Preconditioners in spectral approximation",



// //Name of the journals

// "Indian Journal of Pure and Applied Mathematics", "2021",
// "Partial Differential Equations in Applied Mathematics", "2021",
// "The Monatshefte fur Mathematik", "2021",
// "Banach Journal of Mathematical Analysis", "2021",
// "IJIE(Inderscience)", "2020",
// "Italian journal of pure and applied mathematics", "2020",
// "Journal of Mathematical and Computational Science", "2020",
// "Journal of Pure and Applied Algebra", "2020",
// "Electronic Journal of Graph Theory and Applications", "2020",
// "Discrete Mathematics Algorithms and Applications", "2020",
// "Indian Journal of Pure and Applied Mathematics", "2020",
// "Mathematical Programming, Springer", "2020",
// "Malaya Journal of Matematik", "2020",
// "Malaya Journal of Matematik", "2020",
// "Journal of Analysis", "2020",
// "Journal of Analysis", "2020",
// "IEEE, International conference RTEICT '18", "2019",
// " International Journal of Recent Technology and Engineering", "2019",
// "IEEE Intelligent systems proceedings", "2019",
// "Journal of Homotopy and Related Structures", "2019",
// "Communications in Algebra", "2019",
// "Journal of Noncommutative Geometry", "2019",
// "The Journal of Analysis", "2019",
// "Complex Analysis and Operator Theory", "2018",
// "Bulletin of Kerala Mathematical Association", "2018",
// "Int. J. Appl. Comput. Math.", "2018",
// "Discrete Applied Mathematics", "2018",
// "Journal of computer and Mathematical sciences", "2018",
// "International journal of applied Engineering research", "2018",
// "Linear Algebra and its Applications ", "2018",
// "Proceedingds of the Indian Academy of Sciences - Mathematical Sciences", "2018",
// "Annals of Functional Analysis", "2018",
// "Bulletin of Australian Mathematical Society", "2018",
// "Linear Algebra and its Applications", "2018",
// "Discussions Mathematicae Graph Theory", "2018",
// "Advances in Fuzzy Mathematics", "2017",
// "International Journal of Advanced Scientific Research and Management(IJASRM)", "2017",
// "IEEE Xplore", "2017",
// "Applied Mathematics and Information Sciences", "2017",
// "International Journal of Pure and Applied Mathematics", "2017",
// "Electronic Notes in Discrete Mathematics", "2017",
// "International journal of pure and applied mathematics", "2017",
// "Linear and Multilinear Algebra", "2017",
// "International Journal of Applied and Computational Mathematics", "2017",
// "Annals of Functional Analysis", "2017",
// "Tbilisi Mathematical Journal", "2017",
// "Journal of Combinatorial Optimization", "2017",
// "Electronic Journal of Graph Theory and Applications", "2017",
// "Journal of Combinatorial Optimization", "2017",
// "AKCE International Journal of Graphs and Combinatorics", "2016",
// "Discrete Mathematics and Theoretical Computer Science", "2016",
// "Journal of Combinatorial Mathematics and Combinatorial Computation", "2016",
// "Discrete Mathematics, Algorithms and Applications", "2016",
// "Asian-European Journal of Mathematics", "2016",
// "AIP Conference Proceedings", "2016",
// "Discrete Applied Mathematics", "2016",
// "Annals of Functional Analysis", "2016",

//Year of publication


let publications = [
  ["Spectrum of anti-Gallai Graph of Some Graphs", "Jeepamol J Palathingal, Aparna Lakshmanan S., Gopalapillai Indulal", "Indian Journal of Pure and Applied Mathematics", "2021", "0019-5588", "https://www.scopus.com/sourceid/19900192426", "https://link.springer.com/article/10.1007/s13226-021-00066-z"],
  ["Numerical solution of the viscous Burgers’ equation using Localized Differential Quadrature method", "Athira Babu, Bin Han, Noufal Asharaf", "Partial Differential Equations in Applied Mathematics", "2021", "2666-8181", "https://doaj.org/toc/2666-8181", "https://www.sciencedirect.com/science/article/pii/S2666818121000243 "],
  ["Korovkin-type theorems on B(H) and their applications to function spaces", "Wolfram Bauer, V. B. Kiran Kumar, Rahul Rajan. ", "The Monatshefte fur Mathematik", "2021", "Electronic ISSN\n1436-5081\nPrint  ISSN\n0026-9255", "https://www.scopus.com/sourceid/25167", "https://link.springer.com/article/10.1007/s00605-021-01549-1"],
  ["Boundary representations and rectangular hyperrigidity", "C.S. Arunkumar, P. Shankar, and A.K. Vijayarajan", "Banach Journal of Mathematical Analysis", "2021", "1735-8787 2662-2033", "https://www.scopus.com/sourceid/17300154737", "https://link.springer.com/article/10.1007/s43037-021-00122-0"],
  ["Call detail record-based traffic density analysis using global K-means clustering", "Suja C Nair, Sudeep Elayidom M, Dr.Sasi  Gopalan", "IJIE(Inderscience)", "2020", "1745-3240", "https://www.scopus.com/sourceid/17500155011", "https://www.inderscience.com/info/inarticle.php?artid=104654"],
  ["Rough Approximate operators based on fuzzy soft relation", "Dr. Sasi Gopalan, Anju S Mattam", "Italian journal of pure and applied mathematics", "2020", "2239-0227", "https://www.scopus.com/sourceid/19900192426", "https://ijpam.uniud.it/online_issue/202043/77%20Mattam-Gopalan.pdf"],
  ["Algorithm to compute Transitive closure of fuzzy soft relation", "Dr. Sasi Gopalan, Anju S Mattam", "Journal of Mathematical and Computational Science", "2020", "1927-5307", "https://www.scopus.com/sourceid/21100944441", "http://scik.org/index.php/jmcs/article/view/4291"],
  ["Normality of DSER elementary orthogonal group", "A.A. Ambily and Ravi A. Rao", "Journal of Pure and Applied Algebra", "2020", "0022-4049", "https://www.scopus.com/sourceid/23968", "https://www.sciencedirect.com/science/article/abs/pii/S0022404919302968"],
  ["Two Classes of Non-Leech Trees", "Seena Varghese, Aparna Lakshmanan S., S. Arumugam", "Electronic Journal of Graph Theory and Applications", "2020", "2338-2287", "https://www.scopus.com/sourceid/21100818724", "https://www.ejgta.org/index.php/ejgta/article/view/706"],
  ["The Double Roman Domination Number of Generalized Sierpinski Graphs", "Anu V., Aparna Lakshmanan S.", "Discrete Mathematics Algorithms and Applications", "2020", "1793-8309", "https://www.scopus.com/sourceid/21100837973", "https://www.worldscientific.com/doi/10.1142/S1793830920500470"],
  ["Spectrum of Gallai Graph of Some Graphs", "Jeepamol J Palathingal, Gopalapillai Indulal, Aparna Lakshmanan S.", "Indian Journal of Pure and Applied Mathematics", "2020", "0019-5588", "https://www.scopus.com/sourceid/19900192426", "https://link.springer.com/article/10.1007/s13226-020-0499-0#:~:text=The%20Gallai%20graph%20%CE%93(G,not%20lie%20on%20a%20triangle."],
  ["Simple bilevel programming and extensions", "Stephan Dempe, Nguyen Dinh, Joydeep Dutta and Tanushree Pandit", "Mathematical Programming, Springer", "2020", "0025-5610", "https://www.scopus.com/sourceid/28512", "https://link.springer.com/article/10.1007/s10107-020-01509-x"],
  ["The lattice of pre-complements of a classic interval valued fuzzy graph", "SHERY FERNANDEZ            DEEPTHI MARY TRESA S DIVYA MARY DAISE S", "Malaya Journal of Matematik", "2020", "ISSN (P)      2319–3786 2321–5666", "http://www.malayajournal.org/", "https://www.malayajournal.org/articles/MJM08030102.pdf"],
  ["The Chain structure of intuitionistic level subgroups in cyclic groups of order pq", "SHERY FERNANDEZ            DEEPTHI MARY TRESA S DIVYA MARY DAISE S", "Malaya Journal of Matematik", "2020", "ISSN (P)      2319–3786 2321–5666", "http://www.malayajournal.org/", "https://www.malayajournal.org/archive/selected_article.php?id=1216"],
  ["Hyperrigid generators in C * -algebras", "P. Shankar ", "Journal of Analysis", "2020", "2367-2501", "https://www.scopus.com/sourceid/21101041404", "https://link.springer.com/article/10.1007/s41478-019-00199-9"],
  ["Hilbert modules characterization for weak hyperrigid operator\nSystems", "P. Shankar and A. K. Vijayarajan", "Journal of Analysis", "2020", "2367-2501", "https://www.scopus.com/sourceid/21101041404", "https://link.springer.com/article/10.1007/s41478-020-00220-6"],
  ["An Encryption based Security Enhancer Tool for IaaS\nApplications in Cloud Computing", "Viji Gopal,M Sudheep Elayidom,Varghese Paul,Sasi Gopalan", "IEEE                        International conference RTEICT '18", "2019", "", "https://www.researchgate.net/publication/339560109\
  _An_Encryption_based_Security_Enhancer_Tool_for_IaaS_Applications_in_Cloud_Computing", "https://ieeexplore.ieee.org/document/9012425"],
  ["KM-MBFO: A Hybrid Hadoop Map Reduce Approach for Clustering Big Data by Adopting Modified Bacterial Foraging Optimization Algorithm", "Suja C Nair C Nair, Dr. Sudheep Elayidom M Elayidom M and Dr. Sasi Gopalan Gopalan", " International Journal of Recent Technology and Engineering", "2019", "ISSN: 2277-3878", "https://www.scopus.com/sourceid/21100889873", "https://www.ijrte.org/wp-content/uploads/papers/v8i2S11/B10240982S1119.pdf"],
  ["VC Dimension Based Fuzzy Sigmoid Neural Network (VC-FSNN)", "Linu Pinto; Sasi Gopalan; S. Sundararajan", "IEEE Intelligent systems proceedings", "2019", "1541-1672", "https://www.scopus.com/sourceid/110111", "https://ieeexplore.ieee.org/document/8710465"],
  ["Yoga of commutators in DSER elementary orthogonal group", "A.A. Ambily", "Journal of Homotopy and Related Structures", "2019", "2193-8407", "https://www.scopus.com/sourceid/21100211731", "https://link.springer.com/article/10.1007/s40062-018-0223-5"],
  ["Simple ﬂat Leavitt path algebras are von Neumann regular", "A.A. Ambily, Roozbeh Hazrat and Huanhuan Li", "Communications in Algebra", "2019", "0092-7872", "https://www.scopus.com/sourceid/25800", "https://www.tandfonline.com/doi/full/10.1080/00927872.2018.1513015"],
  ["Non commutative Coarse Geometry", "Tathagata Banerjee, Ralf Meyer", "Journal of Noncommutative Geometry", "2019", "1117-1149", "https://www.scopus.com/sourceid/17800156749", "https://www.ems-ph.org/journals/show_abstract.php?issn=1661-6952&vol=13&iss=3&rank=8&p403=1"],
  ["A short survey on preconditioners and Korovkin- type theorems", "V. B. Kiran Kumar, M. N. N. Namboodiri, Rahul Rajan. ", "The Journal of Analysis", "2019", "2367-2501", "https://ugccare.unipune.ac.in/Apps1/User/WebA/ViewDetails?JournalId=101001136&flag=Search", "https://link.springer.com/article/10.1007/s41478-019-00207-y"],
  ["Approximation of entropy numbers", "Deepesh K.P., V. B. Kiran Kumar. ", "Complex Analysis and Operator Theory ", "2019", "Electronic ISSN\n1661-8262 Print  ISSN\n1661-8254", "https://www.scopus.com/sourceid/5700165206", "https://link.springer.com/article/10.1007/s11785-019-00946-7"],
  ["On the category of R-modules over non commutative rings", "Dr. P G Romeo and  P.R Sreejamole", "Bulletin of Kerala Mathematical Association", "2018", "0973-2721", "https://drive.google.com/file/d/1PKaTo9Lq2d8bEg7pNy9oBopkn9q_7ACD/view?usp=sharing", "https://drive.google.com/file/d/1PKaTo9Lq2d8bEg7pNy9oBopkn9q_7ACD/view?usp=sharing"],
  ["Study of Multiplication operator on H1\n2H􀀀12", "A. Noufal", "Int. J. Appl. Comput.\nMath.", "2018", "2349-5103", "https://www.scopus.com/sourceid/21100899436", "https://link.springer.com/article/10.1007/s40819-018-0576-9"],
  ["Double Roman Domination Number", "Anu V., Aparna Lakshmanan S", "Discrete Applied Mathematics", "2018", "0166-218X", "https://www.scopus.com/sourceid/25890", "https://www.sciencedirect.com/science/article/abs/pii/S0166218X18301173"],
  ["The doze optimization of nano silver on Salmonella Typhmurium  using fuzzy mathematics", "SHERY FERNANDEZ            BENNY K J", "Journal of computer and Mathematical sciences", "2018", "ISSN : 0976-5727(Print),                  ISSN : 2319-8133(Online), ", "http://compmath-journal.org/", "http://compmath-journal.org/articles/detail/736/The-Doze-Optimization-of-Nano-Silver-on-Salmonella-Typhmurium-Through-Fuzzy-Mathematics/Shery-Fernandez-and-Benny-K-J-.html"],
  ["Classic and Non-classic Interval Valued Fuzzy Graphs", "SHERY FERNANDEZ            DEEPTHI MARY TRESA S     DIVYA MARY DAISE S", "International journal of applied Engineering research", "2018", "ISSN : 0973-4562(Print),                  ISSN : 0973-9769(Online), ", "https://www.scopus.com/sourceid/21100217234", "https://www.ripublication.com/ijaerspl2018/ijaerv13n3spl_01.pdf"],
  ["A Korovkin-type theory for non-self-adjoint Toeplitz operators", "V. B. Kiran Kumar, M. N. N. Namboodiri, Rahul Rajan ", "Linear Algebra and its Applications ", "2018", "0024-3795", "https://www.scopus.com/sourceid/24475", "https://www.sciencedirect.com/science/article/pii/S0024379517306821"],
  ["Quasi hyperrigidity and weak peak points for non-commutative\noperator systems", "M. N. N. Namboodiri, S. Pramod, P. Shankar and A. K. Vijayarajan", "Proceedingds of the Indian Academy of Sciences - Mathematical Sciences", "2018", "0973-7685 0253-4142", "https://www.scopus.com/sourceid/23177", "https://link.springer.com/article/10.1007/s12044-018-0430-3"],
  ["Tensor products of hyperrigid operator systems", "P. Shankar and A. K. Vijayarajan", "Annals of Functional Analysis", "2018", "2008-8752 2639-7390", "https://www.scopus.com/sourceid/21100286971", "https://projecteuclid.org/journals/annals-of-functional-analysis/volume-9/issue-3/Tensor-products-of-hyperrigid-operator-systems/10.1215/20088752-2017-0043.short"],
  ["The Domination Game on Split Graphs", "Tijo James, Sandi Klavzar, A Vijayakumar", "Bulletin of Australian Mathematical Society", "2018", "0004-9727", "https://www.scopus.com/sourceid/25244", "https://www.cambridge.org/core/journals/bulletin-of-the-australian-mathematical-society/article/abs/domination-game-on-split-graphs/85FEB8AC20541451C0F354BB9F2179C7"],
  ["Distance Energy Change in bipartite graph due to edge deletion", "Wasin So, Anu Varghese, A Vijayakumar", "Linear Algebra and its Applications ", "2018", "0024-3795", "https://www.scopus.com/sourceid/24475", "https://www.sciencedirect.com/science/article/abs/pii/S0024379518302374"],
  ["Power domination in Knodel graphs and Hanoi Graphs", "Seethu Varghese, M Hinz, A Vijayakumar", "Discussions Mathematicae Graph Theory", "2018", "1234-3099", "https://www.scopus.com/sourceid/19700180503", "https://www.semanticscholar.org/paper/Power-Domination-in-Kn%C3%B6del-Graphs-and-Hanoi-Graphs-Hinz-Varghese/6c73bc540666f7440af9ee07676f2e0ba37f7e4a"],
  ["Product of Fuzzy Soft Groups", "Anju.S.Mattom  and Sasi Gopalan", "Advances in Fuzzy Mathematics", "2017", "ISSN 0973-533X, Volume No.12, pp.205-214", "https://scholar.google.co.in/citations?user=4Zm_kl8AAAAJ&hl=en", "https://www.ripublication.com/afm17/afmv12n2_05.pdf"],
  ["Design and Implementation of  Traffic Analysis and Prediction system using CDR Data", "Suja C Nair , Sudeep Elayidom and Sasi Gopalan", "International Journal of Advanced Scientific Research and Management(IJASRM)\n", "2017", "ISSN 2455-6378,Vol.2, Issue 5, pp.60-64", "https://docplayer.net/156170741-Design-implementation-of-traffic-analysis-and-prediction-system-using-cdr-data.html", "https://www.semanticscholar.org/paper/\
  DESIGN-%26-IMPLEMENTATION-OF-TRAFFIC-ANALYSIS-AND-CDR-Nair-Elayidom/1545cb646ed3331a09c27e25f0ff91017693c25a"],
  ["Impact of CDR Data Analysis Using Big Data Technologies for Public :An Analysis", "Suja C Nair, Sudeep Elayidom M, Sasi gopalan", "IEEE Xplore", "2017", "ISBN :978-1-5090-4558-7", "https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8014651", "https://ieeexplore.ieee.org/document/8014651"],
  ["Function approximation with deep neural network for image classification in fuzzy domain", "Gopalan, S., Pinto, L., Sheela, C., Arun Kumar, M.N.", "Applied Mathematics and Information Sciences", "2017", "1935-0090", "https://www.scopus.com/sourceid/21100197928", "http://www.naturalspublishing.com/files/published/\
  4153m6l5j6vb8h.pdf#:~:text=Image%20classification%20is%20a%20complex,many%20factors%20affecting%20its%20process.&text=This%20work%20proposes%20a%20new,by%20defining%20a%20distance%20measure."],
  ["Interpose Detection Using Complete Lattice Approach of Mathematical Morphology", "Nisha A B,Dr.Sasigopalan", "International Journal of Pure and Applied Mathematics", "2017", "ISSN 1311-8080 (printed version)", "https://www.scopus.com/sourceid/23178", "http://acadpubl.eu/jsi/2017-117-11-14/articles/11/42.pdf"],
  ["Gallai and anti-Gallai graph operators", "Jeepamol J. Palathingal, Aparna Lakshmanan S.", "Electronic Notes in Discrete Mathematics", "2017", "1571-0653", "https://www.scopus.com/sourceid/4700152427", "https://www.sciencedirect.com/science/article/abs/pii/S157106531730344X"],
  ["The doze optimization through fuzzy mathematics", "SHERY FERNANDEZ            BENNY K J", "International journal of pure and applied mathematics", "2017", "ISSN : 1311-8080(Print)              ISSN : 1314-3395(Online)", "https://www.scopus.com/sourceid/23178", "https://www.acadpubl.eu/jsi/2017-117-11-14/articles/14/14.pdf"],
  ["A note on discrete Borg-type theorems. ", "V. B. Kiran Kumar and G. Krishna Kumar ", "Linear and Multilinear Algebra", "2017", "Electronic ISSN\n1563-5139\nPrint  ISSN\n0308-1087", "https://www.scopus.com/sourceid/24476", "https://www.tandfonline.com/doi/full/10.1080/03081087.2017.1356801"],
  [" Real powers of bounded linear operators \u2028\n", "Sabu Sebastian and V. B. Kiran Kumar \u2028\n", "International Journal of Applied and Computational Mathematics", "2017", "Electronic ISSN\n2199-5796\nPrint  ISSN\n2349-5103", "https://www.scopus.com/sourceid/21100899436", "https://link.springer.com/article/10.1007%2Fs40819-015-0114-y"],
  ["Hyperrigid operator systems and Hilbert modules", "P. Shankar and A. K. Vijayarajan", "Annals of Functional Analysis", "2017", "2008-8752 2639-7390", "https://www.scopus.com/sourceid/21100286971", "https://projecteuclid.org/journals/annals-of-functional-analysis/volume-8/issue-1/Hyperrigid-operator-systems-and-Hilbert-modules/10.1215/20088752-3773182.short"],
  ["Separating and quasi hyperrigid operator systems in C*-algebras", "S. Pramod, P. Shankar and A. K. Vijayarajan", "Tbilisi Mathematical Journal", "2017", "1512-0139", "https://mjl.clarivate.com/search-results", "https://projecteuclid.org/journals/tbilisi-mathematical-journal/volume-10/issue-4/Separating-and-quasi-hyperrigid-operator-systems-in-C-algebras/10.1515/tmj-2017-0045.short"],
  ["The diameter variability of the product graphs", "Chitra M R, A Vijayakumar", "Journal of Combinatorial Optimization", "2017", "1021-1024", "https://www.scopus.com/sourceid/28499", "https://www.worldscientific.com/doi/abs/10.1142/S1793830914500013"],
  ["On an edge partition and root graphs of some classes of line graphs", "Pravas K, A Vijayakumar", "Electronic Journal of Graph Theory and Applications", "2017", "2338-2287", "https://www.scopus.com/sourceid/21100818724", "https://www.ejgta.org/index.php/ejgta/article/view/263"],
  ["Convex median and anti-median at prescribed distance", "Pravas K, A Vijayakumar", "Journal of Combinatorial Optimization", "2017", "1021-1024", "https://www.scopus.com/sourceid/28499", "https://link.springer.com/article/10.1007/s10878-016-0022-z"],
  ["Some network topological notions of the Mycielskian of a graph", "Savitha K S, A Vijayakumar", "AKCE International Journal of Graphs and Combinatorics", "2016", "0972-8600", "https://www.scopus.com/sourceid/19900193225", "https://www.tandfonline.com/doi/full/10.1016/j.akcej.2016.02.005"],
  ["Heredity for generalised power domination", "Paul Dorbec, Seethu Varghese, A Vijayakumar", "Discrete Mathematics and Theoretical Computer Science", "2016", "1365-8050", "https://www.scopus.com/sourceid/78470", "https://www.semanticscholar.org/paper/Heredity-for-generalized-power-domination-Dorbec-Varghese/f527ad65e55d439df66d18da41e9baf83dcf09ac"],
  ["The diameter variability of product graphs", "Chitra M R, A Vijayakumar", "Journal of Combinatorial Mathematics and Combinatorial Computation", "2016", "0835-3026", "https://www.scopus.com/sourceid/19700186819", "https://www.worldscientific.com/doi/10.1142/S1793830914500013"],
  ["The k- power bondage number of a graph", "Seethu Varghese, A Vijayakumar", "Discrete Mathematics, Algorithms and Applications", "2016", "1793-8309", "https://www.scopus.com/sourceid/21100837973", "https://www.worldscientific.com/doi/abs/10.1142/S1793830916500646"],
  ["Component factors of the Cartesian product of graphs", "Chitra M R, A Vijayakumar", "Asian-European Journal of Mathematics", "2016", "1793-5571", "https://www.scopus.com/sourceid/21100198431", "https://www.worldscientific.com/doi/abs/10.1142/S1793557116500418?journalCode=aejm"],
  ["A Mathematical Model of Neuro Fuzzy Approximation in image Classification", "Dr.Sasi Gopalan, Linu Pinto , Sheela.C, Arun Kumar", "AIP Conference Proceedings", "2016", "Volume 1738 Article Number 480068  ", "https://doi.org/10.1063/1.4952304", "https://aip.scitation.org/doi/10.1063/1.4952304"],
  ["Induced cycles in triangle graphs", "Aparna Lakshmanan S., Cs. Bujtas, Zs. Tuza", "Discrete Applied Mathematics", "2016", "0166-218X", "https://www.scopus.com/sourceid/25890", "https://www.sciencedirect.com/science/article/pii/S0166218X15005818"],
  ["Preconditioners in spectral approximation \u2028\n", "V. B. Kiran Kumar ", "Annals of Functional Analysis", "2016", "Electronic ISSN\n2008-8752\nPrint  ISSN\n2639-7390", "https://www.scopus.com/sourceid/21100286971", "https://projecteuclid.org/journals/annals-of-functional-analysis/volume-7/issue-2/Preconditioners-in-spectral-approximation/10.1215/20088752-3506079.full"],
  ["Italian Domination and Perfect Italian Domination on Sierpinski Graphs", "Jismy Varghese, Anu V., Aparna Lakshmanan S.", "Journal of Discrete Mathematical Sciences and Cryptography", "2021", "", "", "https://www.tandfonline.com/doi/abs/10.1080/09720529.2021.1933705"],
  ["Leech Index of a Tree", "Seena Varghese, Aparna Lakshmanan S., S. Arumugam", "Journal of Discrete Mathematical Sciences and Cryptography", "2021", "", "", "https://www.tandfonline.com/doi/abs/10.1080/09720529.2020.1800217?journalCode=tdmc20"],
  ["Impact of Some Graph Operators on Double Roman Domination Number", "Anu V., Aparna Lakshmanan S.", "International Journal of Combinatorial Graph Theory and Applications", "2021", ""],
  ["A Comparative Study on Various Sharing Among Undergraduates in PreCovid-19 and Covid-19 Period Using Network Parameters", "V. G. Deepa, Aparna Lakshmanan S., V. N. Sreeja", "Lecture Notes in Networks and Systems", "2021", ""],
  
  ["Interval valued Fuzzy graph and Complement Number", "Shery Fernandez, Deepthi Mary Tresa S", " International Digital Conference on Computatinal sciences (CSMCS - 2020),Computations in Computer and Information Science, CCIS, Springer 192-202", "2021", ""],
  ["Intuitionistic level subgroups in cyclic groups of order", "Shery Fernandez, Divya Mary Daise S", "South East Asian Journal of Mathematics and Mathematical Sciences,17(1)", "2021", ""],
  ["Intuitionistic Level Subgroups in the Klein-4 Group", "Shery Fernandez, Divya Mary", "Creative Mathematics and Informatics, 30(2), 164-173", "2021", ""],
  ["On Isomorphisms of Intuitionistic Fuzzy Sets", "Daise S, Deepthi Mary Tresa S Shery Fernandez, Divya Mary Daise S", "Journal of Advanced Mathematical Studies, 15(2), 176-186", "2022", ""],
  ["Impact of Vertex Addition on Italian Domination Number", "Jismy Varghese, Aparna Lakshmanan S.", "Indian Journal of Discrete Mathematics", "2022", ""],
  ["Visualization for Petrov’s odd unitary group", "A.A. Ambily and V.K. Aparna Pradeep", "Linear and Multilinear Algebra", "2022", ""],
]; 
